
  version: '3.0'

  volumes:
    assets:
      external: false
    configs:
      external: false  
    db-data1:
      external: false

  services:
    prod_db:
      image: postgres
      env_file: .env.prod
      volumes:
        - db-data1:/var/lib/postgresql/db-data-pathway-prod

    prod_app:
      build: 
        context: .
        dockerfile: Dockerfile.prod
      env_file: .env.prod
      ports:
        - "3000:3000" 
      volumes:
        - assets:/usr/share/nginx/html
        - configs:/etc/nginx/conf.d
      depends_on:
        - prod_db

    prod_web:
      image: nginx
      env_file: .env.prod
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - assets:/usr/share/nginx/html
        - configs:/etc/nginx/conf.d
      depends_on:
        - prod_app
