  version: '3.0'

  volumes:
    db-data1:
      external: false


  services:
    prod_db:
      image: postgres
      env_file: .env.prod
      volumes:
        - db-data1:/var/lib/postgresql/db-data

    prod_app:
      build: 
        context: .
        dockerfile: Dockerfile.prod
      env_file: .env.prod
      command: bundle exec puma -C config/puma.rb
      ports:
        - "3000:3000" 
      depends_on:
        - prod_db
#    web:
#      build:
#        context: .
#        dockerfile: Dockerfile.nginx
#      links:
#        - app
#      ports:
#        - "80:80"
